### ISSUE TITLE
Weird behavior when resolution increases?

### ISSUE THREAD

**Issue by kmdeck** [CliMA/LandHydrology.jl#35]
<img width="1548" alt="Screen Shot 2021-09-14 at 16 38 09" src="https://user-images.githubusercontent.com/65979205/133348960-52a01231-c4ae-494f-b131-f61c48735621.png">

**Comment by tapios** [comment]
Looks like a numerical instability. Did you try to reduce the timestep?

**Comment by kmdeck** [comment]
hi @tapios :) thanks for looking!

Here is a plot with some more information. As background, the system is settling into hydrostatic equilibrium, and the porosity is 0.5.
<img width="1866" alt="Screen Shot 2021-09-15 at 09 38 39" src="https://user-images.githubusercontent.com/65979205/133474209-07c36040-d4af-4475-8b84-71df8faac648.png">

So as before, increasing resolution in space generates the zig-zag behavior, but if I then increase the time resolution it goes away (the pink and orange lines agree with blue expected line, within their resolution). For fixed resolution, increasing time resolution always should lead to convergence or increased stability. But increasing spatial resolution at fixed timestep does not. I guess this is not super intuitive to me. Maybe it has to do with not resolving the time it takes for information to cross the smaller distances between points in the higher spatial resolution simulation.

The other thing I thought was odd was that these instabilities are somehow in equilibrium (?). The gold line (32days) coincides with the green line (8days)- both exhibit the same numerical issue. Does that make sense? Instability suggests to me something about positive eigenvalues of the linear system describing what happens when the system is perturbed from equilibrium.

**Comment by tapios** [comment]
This is expected behavior, and your intuition is correct: The maximum stable timestep is dictated by the time it takes for a signal to propagate across a grid cell within 1 timestep. This gets shorter the higher the spatial resolution. In your diffusion-controlled problem, the maximum stable timestep is ~\Delta x^2/D, where \Delta x is the resolution and D is the diffusivity. So it decreases quadratically with increasing resolution.
